app/src/main/java/javax/microedition/m3g/Graphics3D.java

Fixes initialization on some Adreno drivers

Fix EGL initialization

---

app/src/main/java/javax/microedition/lcdui/Canvas.java
app/src/main/java/javax/microedition/media/InternalMetaData.java

Replaced `HashMap<Integer, ?>` with `SparseArray` to avoid unnecessary boxing/unboxing. Also I've added alias <kbd>Enter</kbd> key -> FIRE.

Replace hashmaps with sparsearrays

---

app/src/main/java/javax/microedition/shell/ConfigActivity.java

This should fix the issue #308.

Fix cldc, midp and microedition.locale property values

---

app/src/main/java/javax/microedition/lcdui/Canvas.java

Пробовал по всякому, но только при таком варианте нормально сворачивается/разворачивается.

Fixed crash when minimized with parallel drawing option

---

app/src/main/java/javax/microedition/lcdui/Canvas.java
app/src/main/java/javax/microedition/lcdui/event/EventQueue.java
app/src/main/java/javax/microedition/lcdui/overlay/FpsCounter.java
app/src/main/java/javax/microedition/lcdui/overlay/Layer.java
app/src/main/java/javax/microedition/lcdui/overlay/Overlay.java
app/src/main/java/javax/microedition/lcdui/overlay/OverlayView.java
app/src/main/java/javax/microedition/lcdui/pointer/VirtualKeyboard.java
app/src/main/java/javax/microedition/shell/MicroActivity.java
app/src/main/res/layout/activity_micro.xml

Вынес оверлей в отдельный вью-слой. Клава и фпс теперь обновляются по собственному желанию.  
Насчёт буфера клавы не уверен - мне показалось, что смысла в нём нет.

Overlay improvements

---

app/src/main/java/javax/microedition/lcdui/event/EventQueue.java

Это закрывает проблему https://4pda.ru/forum/index.php?showtopic=824201&view=findpost&p=82781970  
P.S. Гипотетически эта же причина может быть и у #457

Removed unnecessary decrement of counter when event is skipped.

---

app/src/main/java/ru/playsoftware/j2meloader/MainActivity.java
app/src/main/java/ru/playsoftware/j2meloader/applist/AppsListFragment.java
app/src/main/java/ru/playsoftware/j2meloader/util/JarConverter.java

Move the file URI conversion method to the worker thread to avoid blocking the main thread
eg. Galaxy on fire 2 or some S60V5 game has a size of  more than 10M, Convert URI on the main thread may cause ANR

Move the file URI conversion method to the worker thread

---

app/src/main/java/javax/microedition/shell/MicroActivity.java
app/src/main/java/javax/microedition/shell/MicroLoader.java
app/src/main/res/menu/midlet_canvas.xml
app/src/main/res/menu/midlet_canvas_no_bar.xml
app/src/main/res/values/strings.xml

https://github.com/nikita36078/J2ME-Loader/issues/767

support set fps at runtime

---

app/src/main/java/ru/playsoftware/j2meloader/info/AboutDialogFragment.java

Dear developer:
Hello! I am the creator of issue #834, and I have fixed the aforementioned problem and made this page scrollable. I would genuinely appreciate it if you could kindly revise my code and leave me some advice. Thank you so much for your precious time!
Here are the screenshots after my changes:
Thanks again! Blessings on your day! :)

Made the about screen scrollable

---

app/src/main/java/ru/playsoftware/j2meloader/filepicker/FilteredFilePickerFragment.java
app/src/main/java/ru/woesss/j2me/installer/AppInstaller.java

How about supporting installing app from kjx file?
`kjx` file is an application file format which KDDI developed for Ezweb App.
I wrote some codes for parsing them and it looks to work fine.
But I could not found any official specification documents, so this parser contains some bugs, maybe.
Could you review this?

Feature Request: supporting kjx file

---

app/src/main/java/com/kddi/media/MediaEventListener.java
app/src/main/java/com/kddi/media/MediaPlayerBox.java
app/src/main/java/com/kddi/media/MediaPlayerInterface.java
app/src/main/java/com/kddi/media/MediaResource.java
app/src/main/java/com/kddi/system/PhoneSystem.java
app/src/main/java/javax/microedition/media/MMFConverter.java

Implemented below features.
- `getKeyState` function in `com.kddi.system.PhoneSystem` class
- `com.kddi.media.MediaPlayerBox` to play MMF sound

implementing part of com.kddi packages and adding feature to play MMF sound

---

app/src/main/java/javax/microedition/lcdui/ImageItem.java

ImageItem updateImageView in event

---

app/src/main/java/javax/microedition/lcdui/Displayable.java

Displayable.setTitle fix

---

app/src/main/java/javax/microedition/lcdui/Alert.java

Alert.setIndicator fix

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/nokia/mid/ui/Clipboard.java
app/src/main/java/com/nokia/mid/ui/DeviceControl.java
app/src/main/java/com/nokia/mid/ui/DirectUtils.java
app/src/main/java/com/nokia/mid/ui/FreeSizeFontInvoker.java
app/src/main/java/com/nokia/mid/ui/NotificationActivity.java
app/src/main/java/com/nokia/mid/ui/SoftNotification.java
app/src/main/java/com/nokia/mid/ui/SoftNotificationException.java
app/src/main/java/com/nokia/mid/ui/SoftNotificationImpl.java
app/src/main/java/com/nokia/mid/ui/SoftNotificationListener.java
app/src/main/java/javax/microedition/shell/MicroActivity.java

SofNotification, Clipboard, FreeFontSizeInvoker added, implemented DirectUtils.getFont(int) from S40v6.

Nokiaui api improvements

---

app/src/main/java/ru/playsoftware/j2meloader/config/ConfigActivity.java

Fixed: Some options were not reset when resetting and loading config
Optimization: CompoundDrawables use TextViewCompat function

ConfigActivity Bug Fix and Optimization

---

app/src/main/java/javax/microedition/lcdui/Canvas.java
app/src/main/java/javax/microedition/lcdui/Display.java
app/src/main/java/javax/microedition/shell/MidletSystem.java
app/src/main/java/ru/woesss/j2me/jar/Descriptor.java

Add multitouch support

---

app/src/main/java/com/nokia/mid/payment/DrmResourceInputStream.java
app/src/main/java/com/nokia/mid/payment/IAPClientPaymentException.java
app/src/main/java/com/nokia/mid/payment/IAPClientPaymentListener.java
app/src/main/java/com/nokia/mid/payment/IAPClientPaymentManager.java
app/src/main/java/com/nokia/mid/payment/IAPClientProductData.java
app/src/main/java/com/nokia/mid/payment/IAPClientUserAndDeviceData.java

Add Nokia In-App Purchase API 1.0 (stub)

---

app/src/main/AndroidManifest.xml
app/src/main/java/javax/microedition/location/AddressInfo.java
app/src/main/java/javax/microedition/location/Coordinates.java
app/src/main/java/javax/microedition/location/Criteria.java
app/src/main/java/javax/microedition/location/HelperEnumeration.java
app/src/main/java/javax/microedition/location/Landmark.java
app/src/main/java/javax/microedition/location/LandmarkException.java
app/src/main/java/javax/microedition/location/LandmarkStore.java
app/src/main/java/javax/microedition/location/Location.java
app/src/main/java/javax/microedition/location/LocationException.java
app/src/main/java/javax/microedition/location/LocationListener.java
app/src/main/java/javax/microedition/location/LocationProvider.java
app/src/main/java/javax/microedition/location/LocationProviderImpl.java
app/src/main/java/javax/microedition/location/Orientation.java
app/src/main/java/javax/microedition/location/ProximityListener.java
app/src/main/java/javax/microedition/location/QualifiedCoordinates.java
app/src/main/java/javax/microedition/shell/MicroActivity.java

JSR-179 Implementation

---

app/src/main/assets/defaults/system.props

Matches prop format on a real Nokia phone.
Source: http://www.livetrack24.com/statistics.php

Update microedition.platform prop

---

app/src/main/java/com/nokia/mid/sound/Sound.java

Not tested, someone test pls
https://mega.nz/file/51FkXbwD#EffiS1T8gM5gLTIVc_nvsHzqeXhx8XMhuRUkZqR6pzU

Make nokia sound handle endOfMedia update (Harry Potter 3 fix)

---

app/src/main/java/javax/microedition/lcdui/Alert.java
app/src/main/java/javax/microedition/lcdui/ChoiceGroup.java
app/src/main/java/javax/microedition/lcdui/DateField.java
app/src/main/java/javax/microedition/lcdui/Display.java
app/src/main/java/javax/microedition/lcdui/TextFieldImpl.java
app/src/main/java/javax/microedition/shell/MicroActivity.java

Closes #1025 
Closes #1024 
Closes #1027

lcdui fixes

---

app/src/main/java/javax/microedition/lcdui/Alert.java

Fix alerts returning to the old screen after dismiss if screen is already changed by the application

Alert return screen fix
